import { 
  API_PRODUCTION_HOSTNAME, API_PRODUCTION_PATHNAME_PREFIX,
  API_DEVELOPMENT_HOSTNAME, API_DEVELOPMENT_PATHNAME_PREFIX, API_DEVELOPMENT_PORT, 
  GET_FILES_API_ROUTE, GET_PROJECTS_API_ROUTE, SEND_EMAIL_API_ROUTE, 
  DOCKER_BACKEND_SERVICE_NAME 
} 
from "./constants";

function getPathAPI (
  route : typeof GET_FILES_API_ROUTE | typeof GET_PROJECTS_API_ROUTE | typeof SEND_EMAIL_API_ROUTE
) {
  if(process.env.DEV_MODE === 'local') {
    return `http://${API_DEVELOPMENT_HOSTNAME}:${API_DEVELOPMENT_PORT}/${API_DEVELOPMENT_PATHNAME_PREFIX}/${route}`;
  }
  if(process.env.DEV_MODE === 'docker') {
      return `http://${DOCKER_BACKEND_SERVICE_NAME}:${API_DEVELOPMENT_PORT}/${API_DEVELOPMENT_PATHNAME_PREFIX}/${route}`;
  }
  return `https://${API_PRODUCTION_HOSTNAME}/${API_PRODUCTION_PATHNAME_PREFIX}/${route}`;
}

export default getPathAPI;
